[package]
name = "orbisat-components"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"

[dependencies]
orbisat = { path = "../orbisat" }
orbipacket = { git = "https://github.com/orbisat-oeiras/orbipacket-rs.git", features = [
    "defmt",
] }

embassy-sync = "0.7.2"
embassy-time = { version = "0.5.0", features = ["defmt"] }
defmt = "1.0.1"

thiserror = { version = "2.0.18", default-features = false }

### Components
bme280 = { version = "0.5.1", features = ["defmt"] }
mma8x5x = { git = "https://github.com/eldruin/mma8x5x-rs", version = "0.1.1" }
nmea = { version = "0.7.0", features = ["GNSS"], default-features = false }
embedded-io-async = "0.7.0"
