[package]
name = "orbisat-firmware"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"

[dependencies]
orbisat = { path = "../orbisat" }
orbisat-components = { path = "../orbisat-components" }
orbisat-firmware-config = { path = "../orbisat-firmware-config" }

orbipacket = { git = "https://github.com/orbisat-oeiras/orbipacket-rs.git", features = [
    "defmt",
] }

defmt = "1.0.1"

embassy-executor = { version = "0.9.1", features = ["defmt"] }
embassy-time = { version = "0.5.0", features = ["defmt"] }
embassy-sync = "0.7.2"

esp-hal = { version = "1.0.0", features = ["defmt", "unstable"] }
esp-rtos = { version = "0.2.0", features = ["defmt", "embassy"] }
esp-bootloader-esp-idf = { version = "0.4.0", features = ["defmt"] }
esp-backtrace = { version = "0.18.1", features = ["defmt", "panic-handler"] }
esp-println = { version = "0.16.1", features = ["defmt-espflash"] }
static_cell = "2.1.1"

[features]
# Enable selection of ESP target
default = ["esp32"]
esp32 = [
    "esp-hal/esp32",
    "esp-rtos/esp32",
    "esp-bootloader-esp-idf/esp32",
    "esp-backtrace/esp32",
    "esp-println/esp32",
]
esp32s3 = [
    "esp-hal/esp32s3",
    "esp-rtos/esp32s3",
    "esp-bootloader-esp-idf/esp32s3",
    "esp-backtrace/esp32s3",
    "esp-println/esp32s3",
]
