[package]
name = "orbisat"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"

[dependencies]
orbipacket = { git = "https://github.com/orbisat-oeiras/orbipacket-rs.git", features = [
    "defmt",
] }
orbisat-firmware-config = { path = "../orbisat-firmware-config" }

embassy-sync = "0.7.2"
defmt = "1.0.1"
