[package]
name = "orbisat"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"

[dependencies]
orbipacket = { git = "https://github.com/orbisat-oeiras/orbipacket-rs.git", features = [
    "defmt",
] }
orbisat-firmware-config = { path = "../orbisat-firmware-config" }

embassy-sync = "0.8.0"
embassy-futures = "0.1.2"
embassy-time = { version = "0.5.0", features = ["defmt"] }
embedded-hal = "1.0.0"
defmt = "1.0.1"
thiserror = { version = "2.0.18", default-features = false }
heapless = "0.9.3"
